name: ubuntu_openmpi

on:
  push:
    branches: master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.1'
      - 'docs/**'
  pull_request:
    branches: master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.1'
      - 'docs/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up dependencies
          run: |
            sudo apt-get update
            sudo apt-get install automake autoconf libtool libtool-bin m4
            # mpi
            sudo apt-get install openmpi-bin
            # zlib
            sudo apt-get install zlib1g-dev
            autoconf --version
            automake --version
            libtool --version
            gcc --version
        - name: Build PnetCDF
          run: |
            WORKDIR=$(pwd)
            mkdir -p /dev/shm/pnetcdf_output
            autoreconf -i
            ./configure --enable-option-checking=fatal \
                        --enable-profiling \
                        pnc_ac_debug=yes \
                        --enable-burst_buffering \
                        --enable-subfiling \
                        --enable-shared \
                        --enable-debug \
                        --enable-thread-safe \
                        --with-pthread \
                        TESTMPIRUN="mpiexec --oversubscribe -n NP" \
                        TESTOUTDIR=/dev/shm/pnetcdf_output
            make -j 8 tests
        - name: Print config.log
          if: ${{ failure() }}
          run: |
            WORKDIR=$(pwd)
            cat ${WORKDIR}/config.log
        - name: Test PnetCDF
          run: |
            WORKDIR=$(pwd)
            make check
            make ptests
            make distcheck DISTCHECK_CONFIGURE_FLAGS="--silent TESTOUTDIR=/dev/shm/pnetcdf_output"
        - name: Print log files
          if: ${{ always() }}
          run: |
            WORKDIR=$(pwd)
            cat ${WORKDIR}/test/*/*.log
        - name: Cleanup
          if: ${{ always() }}
          run: |
            make -s distclean
            rm -rf /dev/shm/pnetcdf_output

